os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # Your first program

        First, open the editor. Type one line of code to make your
        program show the words `Hello world!` when it is run.

        Remember to press the "check" button to verify your answer!
      filesystem: fs1.yaml
      editor:
          - {name: hello.py, contents: ""}
          - {name: test.py, contents: test.py}
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: hello.py, contents: hello1.py}
    - question_format: md
      question: >
        # Your first program

        Now run your program in the terminal.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python hello.py"
            termoutput: t1.txt
    - question_format: md
      question: >
        # Your first program

        Now change your program to show the words, `Goodbye world!`.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: hello.py, contents: hello2.py}
    - question_format: md
      question: >
        # Change folder

        Now run your modified program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python hello.py"
            termoutput: t2.txt

