os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # List growth

        Run the program `bigger.py`.
      editor:
          - {name: bigger.py, contents: bigger1.py}
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python bigger.py"
            termoutput: t1.txt
    - question_format: md
      question: |
        # List growth

        Add an item to `things`. But not on line 1!

        Insert a new line _above_ `print` and add code
        there to include "sandals" in `footwear`.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: bigger.py, contents: bigger2.py}
    - question_format: md
      question: |
        # List growth

        Good work. Now run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python bigger.py"
            termoutput: t2.txt
    - question_format: md
      question: |
        # List growth

        Add another item to `things`.

        Make a new line after where you added "sandals",
        and add "boots" to `footwear`.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: bigger.py, contents: bigger3.py}
    - question_format: md
      question: |
        # List growth

        Nice! Now run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python bigger.py"
            termoutput: t3.txt
