os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # List problem

        Run the program `basic.py`.
      editor:
          - {name: basic.py, contents: basic1.py}
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python basic.py"
            termoutput: t1.txt
    - question_format: md
      question: |
        # List problem

        The code in `basic.py` has a bug.

        The wrong item is being removed from the list of
        `essentials`.

        Go ahead and fix the bug.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: basic.py, contents: basic2.py}
    - question_format: md
      question: >
        # List problem

        Well done! Now run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python basic.py"
            termoutput: t2.txt
