os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # Random numbers

        Random numbers are used in games a lot. Let's make the computer
        _even more_ unpredictable!

        Write a program to print out five random numbers between
        `0.1` and `0.9`.
      filesystem: fs1.yaml
      editor:
          - {name: rand.py, contents: ""}
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: rand.py, contents: rand1.py}
    - question_format: md
      question: >
        # Random numbers

        Now run your program in the terminal.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python rand.py"
            termoutput: t1.txt
    - question_format: md
      question: >
        # Your first program

        Now change your program to print out 15 random _whole numbers_
        between 0 and 10.

        <i class="twfl twfl-smile"></i> In coding, whole numbers are
        called *integers*, and numbers like "2.99" are
        often called *floats*.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: rand.py, contents: rand2.py}
    - question_format: md
      question: >
        # Change folder

        Now run your modified program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python rand.py"
            termoutput: t2.txt

