os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: |
        # Print dict val

        File `printval.py` contains a line of data. The
        data is stored in a `dict`.

        Add a line that will display Mike's age when the
        program is run.
      editor:
          - {name: printval.py, contents: printval1.py}
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: printval.py, contents: printval2.py}
    - question_format: md
      question: >
        # Print dict val

        Run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python printval.py"
            termoutput: t1.txt
    - question_format: md
      question: |
        # Print dict val

        Add a line to the code to display
        Linda's age.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: printval.py, contents: printval3.py}
    - question_format: md
      question: >
        # Print dict val

        Run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python printval.py"
            termoutput: t2.txt
    - question_format: md
      question: |
        # Print dict val

        Add two more lines to display the other two ages. First
        Jane, then Tom.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: printval.py, contents: printval4.py}
    - question_format: md
      question: >
        # Print dict val

        Run your program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python printval.py"
            termoutput: t3.txt
