os: windows # windows | linux | osx | all
level: 1 # Difficulty level 1-5
status: active # could be active | disabled | draft
setup:
    script: mkfs.py  # This gets run to set up the env for term cmds.
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # The `datetime` library

        In the editor, use the `datetime` library to display today's
        date.
      filesystem: fs1.yaml
      editor:
          - {name: showdate.py, contents: ""}
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: showdate.py, contents: showdate1.py}
    - question_format: md
      question: >
        # The `os` library

        Now run your program in the terminal.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python showdate.py"
            termoutput: t1.txt
    - question_format: md
      question: >
        # The `datetime` library

        Nice! Change your code to print out today's date _and_ time.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: showdate.py, contents: showdate2.py}
    - question_format: md
      question: >
        # Change folder

        Now run your modified program.
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python showdate.py"
            termoutput: t2.txt
    - question_format: md
      question: >
        # The `datetime` library

        Good work. The info is there but it's a bit ugly. Change
        your program to make the date and time a bit more friendly.
      answer: # This is the answer for this q, and setup for next q
            editor:
                - {name: showdate.py, contents: showdate3.py}
    - question_format: md
      question: >
        # Change folder

        Now run your modified program. The output will look nicer!
      answer: # This is the answer for this q, and setup for next q
            term_format: txt
            term: "python showdate.py"
            termoutput: t3.txt
